---
title: "gapminder-wrangle"
author: "sdt"
date: "2020/7/9"
output: pdf_document
---

```{r setup,message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

```{r}
gapminder <- readr::read_csv('data/gapminder.csv')
```

```{r}
gap_max_life_exp <- gapminder %>%
dplyr::select(-continent, -lifeExp) %>% # or select(country, year
dplyr::group_by(country) %>%
dplyr::mutate(gdp = pop * gdpPercap) %>%
dplyr::summarize(max_gdp = max(gdp)) %>%
dplyr::ungroup()
```

```{r}
gap_max_life_exp
```

```{r}
gap_wide <- readr::read_csv('data/gapminder_wide.csv')
```


```{r}
gap_long <- gap_wide %>%
gather(key = obstype_year,
value = obs_values,
-continent, -country) %>%
separate(obstype_year,
into = c('obs_type','year'),
sep = "_",
convert = TRUE)
```

```{r}
canada_df <- gap_long %>%
filter(obs_type == "lifeExp",
country == "Canada")
ggplot(canada_df, aes(x = year, y = obs_values)) +
geom_line()
```

```{r}
life_df <- gap_long %>%
filter(obs_type == "lifeExp",
continent == "Americas") 
ggplot(life_df, aes(x = year, y = obs_values, color = country)) +
geom_line()
```

